#!/bin/sh

if [ $# -lt 2 ]; then
  echo "Usage $0 <filename> <email>"
  exit 1
fi

FILENAME=$1
EMAIL=$2

function encrypt_and_upload () {
    _filename=$1
    PLAINTEXT_DIGEST_ALGORITHM="md5"
    PLAINTEXT_DIGEST=$(md5sum $_filename | awk '{print $1}')
    
    echo "$_filename: $PLAINTEXT_DIGEST"
    
    gpg --output $_filename.gpg --encrypt --recipient $EMAIL $_filename
    
    curl -F "encrypted_file=@$_filename.gpg" -F "plaintext_digest_algorithm=$PLAINTEXT_DIGEST_ALGORITHM" -F "plaintext_digest=$PLAINTEXT_DIGEST" http://localhost:3000/files
    echo
}

encrypt_and_upload $FILENAME

echo "Done."
