#!/bin/sh

if [ $# -lt 2 ]; then
  echo "Usage $0 <filename> <email>"
  exit 1
fi

FILENAME=$1
EMAIL=$2

PLAINTEXT_DIGEST_ALGORITHM="md5"
PLAINTEXT_MD5=$(md5sum $FILENAME | awk '{print $1}')

echo "$FILENAME: $PLAINTEXT_MD5"

gpg --output $FILENAME.gpg --encrypt --recipient $EMAIL $FILENAME

curl -F "encrypted_file=@$FILENAME.gpg" -F "plaintext_digest_algorithm=$PLAINTEXT_DIGEST_ALGORITHM" -F "plaintext_digest=$PLAINTEXT_MD5" http://localhost:3000/files
